apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-zone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: upload-zone
  template:
    metadata:
      labels:
        app: upload-zone
    spec:
      containers:
      - name: upload-zone
        image: <docker-repo>/upload-zone:latest
        ports:
        - containerPort: 3000